on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Wasm
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target wasm32-unknown-unknown

    - name: Run wasm-pack
      run: wasm-pack build

    # Assuming your wasm-pack build outputs to 'pkg' and your static site is in 'dist'
    - name: Install Node.js and npm dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      run: |
        npm install
        npm run build # Or any other command that prepares your 'dist' directory

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
        # Optional: Add CNAME, project_url, etc.
