name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: cargo and wasm-pack tests
        run: |
          cargo test
          wasm-pack test --headless --chrome
          wasm-pack test --headless --firefox

      - name: wasm-pack build
        run: wasm-pack build --release

      - run: cd www && npm install
        name: npm install

      - run: cd www && npm run build
        name: npm build

      - name: setup ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./www/dist