name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: cargo and wasm-pack tests
        run: |
          cargo test
          wasm-pack test --headless --chrome
          wasm-pack test --headless --firefox